#!/usr/bin/env python3
"""Generate cached native quartet paths and one sampled motion contract. No runtime JSON.
Run this file to regenerate; --check also verifies renderer consumption.
"""
import argparse
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
DEFINITION = Path('shared/tagmaster/quartet-loader.json')
ANDROID = Path('Android/TagMaster/src/main/java/depollsoft/tagmaster')
IOS = Path('iOS/tagmaster/tagmaster')


def number(value):
    value = round(value, 8)
    return ('%.8f' % (0 if value == 0 else value)).rstrip('0').rstrip('.') + ('.0' if value == int(value) else '')


def geometry(d):
    n, s = d['notes'], d['staff']
    k = 4 * (math.sqrt(2) - 1) / 3
    angle = math.radians(n['rotationDegrees'])
    def point(x, y):
        x, y = x * n['headRx'], y * n['headRy']
        return (x * math.cos(angle) - y * math.sin(angle), x * math.sin(angle) + y * math.cos(angle))
    head: list[tuple[str, tuple[float, ...]]] = [('M', point(1, 0))]
    for coords in [(1,k,k,1,0,1),(-k,1,-1,k,-1,0),(-1,-k,-k,-1,0,-1),(k,-1,1,-k,1,0)]:
        head.append(('C', sum((point(*coords[i:i+2]) for i in range(0,6,2)), ())))
    head.append(('Z', ()))
    x, half, length = n['stemX'], n['stemWidth'] / 2, n['stemLength']
    head += [('M',(x-half,0)),('L',(x-half,-length)),('L',(x+half,-length)),('L',(x+half,0)),('Z',())]
    staff = []
    for i in range(s['count']):
        y = s['y'] + i * s['spacing']
        staff += [('M',(s['x1'],y)),('L',(s['x2'],y))]
    return head, staff


def samples(d):
    m = d['motion']
    result = []
    for voice in range(d['notes']['count']):
        row = []
        for index in range(m['sampleCount']):
            phase = m['phaseStart'] + (m['phaseEnd'] - m['phaseStart']) * index / (m['sampleCount'] - 1)
            local = (phase - voice * m['stagger'] + 1) % 1
            row.append(-math.sin(local / m['activeFraction'] * math.pi) * m['lift'] if local < m['activeFraction'] else 0)
        row[-1] = row[0]
        result.append(row)
    return result


def outputs(d):
    assert d['artwork']['fit'] == 'uniform-center'
    assert d['motion']['interpolation'] == 'linear'
    assert d['motion']['localPhase'] == '(phase - voice * stagger + 1) % 1'
    assert d['motion']['translationY'] == 'local < activeFraction ? -sin(local / activeFraction * pi) * lift : 0'
    assert d['motion']['repeat'] == 'infinite'
    assert d['path'] == {'ellipse':'four-cubic-beziers','fillRule':'nonzero','stemCap':'butt'}
    n, m, a = d['notes'], d['motion'], d['artwork']
    constants = {'Width':a['width'], 'Height':a['height'], 'Period':m['periodSeconds'], 'PhaseStart':m['phaseStart'], 'PhaseEnd':m['phaseEnd'], 'StaffWidth':d['staff']['width'], 'StaffAlpha':d['staff']['alpha'] / 255}
    vectors = {'X':[n['x'] + i*n['dx'] for i in range(n['count'])], 'Y':[n['y'] + i*n['dy'] for i in range(n['count'])], 'Still':m['stillTranslations']}
    banner = '// Generated by tools/generate_quartet_artwork.py from shared/tagmaster/quartet-loader.json. Do not edit.\n'
    kt = banner + 'package depollsoft.tagmaster\n\nimport android.graphics.Path\n\ninternal object QuartetArtwork {\n'
    h = banner + '#import <UIKit/UIKit.h>\n\n'
    objc = banner + '#import "TMQuartetArtwork.h"\n\n'
    for name, value in constants.items():
        kt += f'    const val {name.upper()} = {number(value)}f\n'
        h += f'FOUNDATION_EXPORT const CGFloat TMQuartet{name};\n'
        objc += f'const CGFloat TMQuartet{name} = {number(value)};\n'
    for name, values in vectors.items():
        kt += f'    val {name.lower()} = floatArrayOf(' + ', '.join(number(v)+'f' for v in values) + ')\n'
        h += f'FOUNDATION_EXPORT const CGFloat TMQuartet{name}[{n["count"]}];\n'
        objc += f'const CGFloat TMQuartet{name}[{n["count"]}] = {{' + ', '.join(number(v) for v in values) + '};\n'
    for name, color in d['colors'].items():
        kt += f'    val {name} = 0xFF{color[1:]}.toInt()\n'
    h += 'FOUNDATION_EXPORT CGColorRef TMQuartetColor(BOOL dark, BOOL staff); // Borrowed sRGB\n'
    objc += 'CGColorRef TMQuartetColor(BOOL dark, BOOL staff) {\n    static CGColorRef colors[4]; static dispatch_once_t once;\n    dispatch_once(&once, ^{\n        CGColorSpaceRef space = CGColorSpaceCreateWithName(kCGColorSpaceSRGB);\n'
    for index, name in enumerate(['lightNote','darkNote','lightStaff','darkStaff']):
        color = d['colors'][name][1:]
        rgba = [int(color[i:i+2],16)/255 for i in (0,2,4)] + [d['staff']['alpha']/255 if index >= 2 else 1]
        objc += f'        CGFloat c{index}[] = {{' + ', '.join(number(v) for v in rgba) + f'}}; colors[{index}] = CGColorCreate(space, c{index});\n'
    objc += '        CGColorSpaceRelease(space);\n    });\n    return colors[(staff ? 2 : 0) + (dark ? 1 : 0)];\n}\n'
    for name, path in zip(['Note','Staff'], geometry(d)):
        kt += f'    val {name.lower()} =\n        Path().apply {{\n'
        h += f'FOUNDATION_EXPORT CGPathRef TMQuartet{name}Path(void); // Borrowed immutable path\n'
        objc += f'CGPathRef TMQuartet{name}Path(void) {{\n    static CGPathRef path; static dispatch_once_t once;\n    dispatch_once(&once, ^{{\n        CGMutablePathRef p = CGPathCreateMutable();\n'
        for command, values in path:
            if command == 'Z':
                kt += '            close()\n'; objc += '        CGPathCloseSubpath(p);\n'
            else:
                kt += f'            {dict(M="moveTo",L="lineTo",C="cubicTo")[command]}(' + ', '.join(number(v)+'f' for v in values) + ')\n'
                objc += f'        {dict(M="CGPathMoveToPoint",L="CGPathAddLineToPoint",C="CGPathAddCurveToPoint")[command]}(p, NULL, ' + ', '.join(number(v) for v in values) + ');\n'
        kt += '        }\n'
        objc += '        path = CGPathCreateCopy(p); CGPathRelease(p);\n    });\n    return path;\n}\n'
    rows = samples(d)
    kt += '    val samples =\n        arrayOf(\n' + ''.join('            floatArrayOf(\n' + ''.join('                '+number(v)+'f,\n' for v in row) + '            ),\n' for row in rows) + '        )\n'
    kt += '''
    fun translation(
        voice: Int,
        phase: Float,
    ): Float {
        val position = phase.coerceIn(PHASESTART, PHASEEND) * (samples[voice].size - 1)
        val index = position.toInt().coerceAtMost(samples[voice].lastIndex - 1)
        return samples[voice][index] + (samples[voice][index + 1] - samples[voice][index]) * (position - index)
    }
}
'''
    h += 'FOUNDATION_EXPORT NSArray<NSNumber *> *TMQuartetSamples(NSUInteger voice);\n'
    objc += 'NSArray<NSNumber *> *TMQuartetSamples(NSUInteger voice) {\n    static NSArray *rows; static dispatch_once_t once;\n    dispatch_once(&once, ^{ rows = @[\n' + ''.join('        @[' + ', '.join('@'+number(v) for v in row) + '],\n' for row in rows) + '    ]; });\n    return rows[voice];\n}\n'
    xml = '<!-- Generated by generate_quartet_artwork.py. Do not edit. -->\n<resources>\n' + f'    <dimen name="quartet_width">{a["width"]}dp</dimen>\n    <dimen name="quartet_height">{a["height"]}dp</dimen>\n</resources>\n'
    return {ANDROID/'QuartetArtwork.kt':kt, IOS/'TMQuartetArtwork.h':h, IOS/'TMQuartetArtwork.m':objc, Path('Android/TagMaster/src/main/res/values/quartet_dimensions.xml'):xml}


def check_consumers(root):
    checks = {
        ANDROID/'TagLoadingView.kt': (['QuartetArtwork.WIDTH', 'QuartetArtwork.HEIGHT', 'QuartetArtwork.PERIOD', 'QuartetArtwork.translation', 'QuartetArtwork.note', 'QuartetArtwork.staff', 'QuartetArtwork.x', 'QuartetArtwork.y', 'QuartetArtwork.still', 'QuartetArtwork.lightNote', 'QuartetArtwork.darkNote', 'QuartetArtwork.lightStaff', 'QuartetArtwork.darkStaff', 'minOf('], ['sin(', 'duration = 2800', 'canvas.drawOval', 'canvas.drawLine', 'md_primary', 'md_on_surface_variant', '/ 216f', '/ 96f']),
        IOS/'DPTagViewController.m': (['TMQuartetWidth','TMQuartetHeight','TMQuartetPeriod','TMQuartetSamples(i)','TMQuartetNotePath()', 'TMQuartetStaffPath()', 'TMQuartetX[i]', 'TMQuartetY[i]', 'TMQuartetStill[i]', 'TMQuartetColor(', 'kCAAnimationLinear', 'MIN('], ['motion.duration = 2.4', 'motion.timingFunctions', 'const CGFloat heights[]', 'CGSizeMake(204, 88)', 'motion.values = @[@0', 'i * 0.16'])
    }
    for path, (required, forbidden) in checks.items():
        text = (root/path).read_text()
        for token in required:
            if token not in text: raise ValueError(f'{path}: missing shared consumer {token}')
        for token in forbidden:
            if token in text: raise ValueError(f'{path}: independent renderer {token}')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    d = json.loads((ROOT/DEFINITION).read_text())
    for path, content in outputs(d).items():
        if args.check:
            if not (ROOT/path).exists() or (ROOT/path).read_text() != content:
                raise SystemExit(f'Generated quartet drift: {path}')
        else:
            (ROOT/path).write_text(content)
    if args.check: check_consumers(ROOT)
    print('Quartet artwork ' + ('checked' if args.check else 'generated'))


if __name__ == '__main__':
    main()
