#!/usr/bin/env python3
"""Offline conversion only. Run from any directory; --check verifies checked-in outputs.
Supports only the canonical file's M/m, c, z grammar and fails on changes.
No runtime parser, third-party package, or required build step. The Android XML is
read-only input; shared/tagmaster/barberpole-loader.json drives checked-in Kotlin
and Objective-C loader outputs. --check verifies both platforms and the launch PDF.
"""
from pathlib import Path
from decimal import Decimal as D
import hashlib
import json
import math
import re
import sys
import xml.etree.ElementTree as ET

app = Path(__file__).resolve().parents[1]
root = app.parents[1]
source = root / 'Android/TagMaster/src/main/res/drawable/ic_barberpole.xml'
xml = source.read_bytes()
node = ET.fromstring(xml)
ns = '{http://schemas.android.com/apk/res/android}'
assert node.attrib[ns + 'viewportWidth'] == '299.75076'
assert node.attrib[ns + 'viewportHeight'] == '513.52234'
assert len(node) == 1
raw = node[0].attrib[ns + 'pathData']
tokens = re.findall(r'[A-Za-z]|[-+]?(?:\d*\.\d+|\d+)', raw)
assert not re.sub(r'[A-Za-z]|[-+]?(?:\d*\.\d+|\d+)|[\s,]', '', raw)
contours = []
x = y = D(0)
start = (x, y)
i = 0
command = None
while i < len(tokens):
    if tokens[i].isalpha():
        command = tokens[i]
        i += 1
    if command in ('M', 'm'):
        a, b = map(D, tokens[i:i+2]); i += 2
        x, y = (a, b) if command == 'M' else (x+a, y+b)
        start = (x, y)
        contours.append([('M', (x, y))])
        command = None
    elif command == 'c':
        values = list(map(D, tokens[i:i+6])); i += 6
        points = tuple(v + (x if j % 2 == 0 else y) for j, v in enumerate(values))
        contours[-1].append(('C', points))
        x, y = points[-2:]
    elif command == 'z':
        contours[-1].append(('Z', ()))
        x, y = start
        command = None
    else:
        raise ValueError(f'Unsupported canonical command {command!r}')
assert len(contours) == 9
assert [len(c)-2 for c in contours] == [48, 8, 7, 5, 10, 13, 12, 7, 12]
fmt = lambda v: f'{v:.2f}'
lines = [f'// Generated by tools/generate_logo_artwork.py; do not hand-edit.',
         f'// Canonical ic_barberpole.xml SHA-256: {hashlib.sha256(xml).hexdigest()}',
         '// All nine contours retain their original order and nonzero winding.',
         '#import "TMLogoArtwork.h"', '',
         'const CGFloat TMLogoWidth = 299.75076, TMLogoHeight = 513.52234;', '',
         'static void TMAppendContour(CGMutablePathRef path, NSUInteger contour) {',
         '    switch (contour) {']
for index, contour in enumerate(contours):
    lines.append(f'        case {index}:')
    for command, points in contour:
        if command == 'Z':
            lines.append('            CGPathCloseSubpath(path);')
        else:
            function = 'CGPathMoveToPoint' if command == 'M' else 'CGPathAddCurveToPoint'
            lines.append(f'            {function}(path, NULL, {", ".join(map(fmt, points))});')
    lines.append('            break;')
lines += ['    }', '}', '', 'static CGPathRef full, silhouette, highlights;',
          'static void TMPrepareLogoPaths(void) {', '    static dispatch_once_t once;',
          '    dispatch_once(&once, ^{',
          '        CGMutablePathRef all = CGPathCreateMutable();',
          '        CGMutablePathRef shine = CGPathCreateMutable();',
          '        for (NSUInteger i = 0; i < 9; i++) {',
          '            CGMutablePathRef contour = CGPathCreateMutable();',
          '            TMAppendContour(contour, i);',
          '            CGPathAddPath(all, NULL, contour);',
          '            if (i == 0) silhouette = CGPathCreateCopy(contour);',
          '            if (i == 1 || i == 2 || i == 7 || i == 8) CGPathAddPath(shine, NULL, contour);',
          '            CGPathRelease(contour);', '        }',
          '        full = CGPathCreateCopy(all);', '        highlights = CGPathCreateCopy(shine);',
          '        CGPathRelease(all);', '        CGPathRelease(shine);', '    });', '}', '',
          'CGPathRef TMLogoFullPath(void) { TMPrepareLogoPaths(); return full; }',
          'CGPathRef TMLogoSilhouettePath(void) { TMPrepareLogoPaths(); return silhouette; }',
          'CGPathRef TMLogoHighlightsPath(void) { TMPrepareLogoPaths(); return highlights; }', '']
outputs = {app / 'tagmaster/TMLogoArtwork.m': '\n'.join(lines).encode()}

# One loader definition, including the exact control-point transform. Do not use
# CGPathGetPathBoundingBox (curve extrema) here: Android computeBounds includes
# Bezier control points. Transform ONCE offline so both renderers receive the same path.
definition = root / 'shared/tagmaster/barberpole-loader.json'
loader_bytes = definition.read_bytes()
try:
    loader = json.loads(loader_bytes)
except ValueError as error:
    raise SystemExit(f"Invalid shared loader JSON: {error}") from error
g = loader['geometry']; motion = loader['motion']
assert source == root / g['source']
assert g['viewport'] == [299.75076, 513.52234]
assert g['clip'] == 'shaft' and g['strokeWidth'] == 0
assert g['fillRule'] == 'nonzero' and g['metalFillRule'] == 'evenOdd'
assert g['stripeScalePivot'] == 'rotated-control-point-bounds-center'
assert loader['fit'] == 'uniform-centered'
assert motion['direction'] == 'positive-local-y' and motion['timing'] == 'linear'
assert motion['repeat'] == 'infinite' and motion['staticPhase'] == 0
assert motion['phaseFormula'] == '(index + normalizedPhase * phaseMultiplier) * stripeStep'
assert motion['evenColor'] == 'red' and motion['oddColor'] == 'blue'
assert loader['colors']['highlights'] == '#00000000'
angle = math.radians(g['stripeAxisRotationDegrees'])
c, s = math.cos(angle), math.sin(angle)
stripe = []
for command, points in contours[g['stripeContour']]:
    rotated = []
    for x, y in zip(points[::2], points[1::2]):
        try:
            rotated.extend([float(x)*c-float(y)*s, float(x)*s+float(y)*c])
        except (ValueError, OverflowError) as error:
            raise SystemExit(f"Invalid stripe coordinate: {error}") from error
    stripe.append((command, rotated))
xs = [x for _, p in stripe for x in p[::2]]
pivot = (min(xs) + max(xs)) / 2
stripe = [(cmd, [(v-pivot)*g['stripeHorizontalScale']+pivot if i % 2 == 0 else v
                  for i, v in enumerate(p)]) for cmd, p in stripe]
metal = [item for index in [g['metalContour']] + g['transparentHighlightContours'] for item in contours[index]]
shaft = g['shaft']
provenance = f'// Shared loader SHA-256: {hashlib.sha256(loader_bytes).hexdigest()}'
values = {'WIDTH': g['viewport'][0], 'HEIGHT': g['viewport'][1],
          'ARTWORK_WIDTH': loader['artworkSize'][0], 'ARTWORK_HEIGHT': loader['artworkSize'][1],
          'COMPACT_HEIGHT': loader['compactArtworkHeight'],
          'COMPACT_WIDTH': loader['artworkSize'][0] * loader['compactArtworkHeight'] / loader['artworkSize'][1],
          'AXIS_ANGLE': motion['axisDegrees'], 'STRIPE_STEP': motion['stripeStep'],
          'PHASE_MULTIPLIER': motion['phaseMultiplier'], 'DURATION_SECONDS': motion['durationSeconds']}
objc_names = {'WIDTH':'TMLogoWidth', 'HEIGHT':'TMLogoHeight', 'ARTWORK_WIDTH':'TMLoaderArtworkWidth',
              'ARTWORK_HEIGHT':'TMLoaderArtworkHeight', 'AXIS_ANGLE':'TMLoaderAxisAngle',
              'STRIPE_STEP':'TMLoaderStripeStep', 'PHASE_MULTIPLIER':'TMLoaderPhaseMultiplier',
              'DURATION_SECONDS':'TMLoaderDurationSeconds',
              'COMPACT_WIDTH':'TMLoaderCompactWidth', 'COMPACT_HEIGHT':'TMLoaderCompactHeight'}
def number(v):
    try:
        return f'{float(v):.8f}'.rstrip('0').rstrip('.') if float(v) != 0 else '0'
    except (ValueError, OverflowError) as error:
        raise SystemExit(f'Invalid native coordinate: {error}') from error
outputs[root / 'Android/TagMaster/src/main/res/values/barberpole_dimensions.xml'] = (
    '<!-- Generated by iOS/tagmaster/tools/generate_logo_artwork.py; do not hand-edit. -->\n'
    '<resources>\n'
    f'    <dimen name="barberpole_compact_width">{number(values["COMPACT_WIDTH"])}dp</dimen>\n'
    f'    <dimen name="barberpole_compact_height">{number(values["COMPACT_HEIGHT"])}dp</dimen>\n'
    '</resources>\n').encode()

def native_path(path, language):
    result = []
    for command, points in path:
        args = ', '.join(number(v) + ('f' if language == 'kt' else '') for v in points)
        if language == 'kt':
            fn = {'M':'moveTo', 'L':'lineTo', 'C':'cubicTo', 'Z':'close'}[command]
            result.append(f'                {fn}({args})')
        else:
            fn = {'M':'CGPathMoveToPoint', 'L':'CGPathAddLineToPoint', 'C':'CGPathAddCurveToPoint', 'Z':'CGPathCloseSubpath'}[command]
            result.append(f'        {fn}(path' + (f', NULL, {args}' if points else '') + ');')
    return result
kt = ['// Generated by iOS/tagmaster/tools/generate_logo_artwork.py; do not hand-edit.',
      lines[1], provenance, 'package depollsoft.tagmaster', '', 'import android.content.res.Resources',
      'import android.graphics.Path', '', '/** Paths derived from ic_barberpole.xml. Cached once, never mutated by renderers. */',
      'internal class BarberPoleLogo(', '    @Suppress("UNUSED_PARAMETER") resources: Resources,', ') {',
      '    val metal: Path get() = metalPath', '    val shaft: Path get() = shaftPath',
      '    val stripe: Path get() = stripePath', '', '    companion object {']
for name, value in values.items(): kt.append(f'        const val {name} = {number(value)}f')
for name, key in [('REPEAT_MIN','repeatMin'), ('REPEAT_MAX','repeatMax')]:
    kt.append(f'        const val {name} = {motion[key]}')
for name, color in loader['colors'].items():
    if name == 'highlights': continue
    key = re.sub(r'([A-Z])', r'_\1', name).upper()
    kt.append(f'        val {key}: Int = 0xFF{color[1:]}.toInt()')
for name, path in [('metal',metal), ('shaft',shaft), ('stripe',stripe)]:
    kt += [f'        private val {name}Path =', '            Path().apply {']
    if name == 'metal': kt.append('                fillType = Path.FillType.EVEN_ODD')
    kt += native_path(path, 'kt') + ['            }']
kt += ['    }', '}', '']
outputs[root / 'Android/TagMaster/src/main/java/depollsoft/tagmaster/BarberPoleLogo.kt'] = '\n'.join(kt).encode()
header = ['// Generated by tools/generate_logo_artwork.py; do not hand-edit.', '#import <UIKit/UIKit.h>', '',
          'NS_ASSUME_NONNULL_BEGIN']
for name in objc_names.values(): header.append(f'FOUNDATION_EXPORT const CGFloat {name};')
header += ['FOUNDATION_EXPORT const NSInteger TMLoaderRepeatMin, TMLoaderRepeatMax;',
           '// Borrowed immutable process-lifetime paths/colors. Never mutate or release.',
           '// Apply drawing transforms to layers or copies, not the shared provider.']
for name in ['TMLogoFullPath','TMLogoSilhouettePath','TMLogoHighlightsPath','TMLoaderMetalPath','TMLoaderShaftPath','TMLoaderStripePath']:
    header.append(f'FOUNDATION_EXPORT CGPathRef {name}(void) CF_RETURNS_NOT_RETAINED;')
header += ['FOUNDATION_EXPORT CGColorRef TMLoaderColor(NSString *name) CF_RETURNS_NOT_RETAINED;', 'NS_ASSUME_NONNULL_END', '']
outputs[app / 'tagmaster/TMLogoArtwork.h'] = '\n'.join(header).encode()
lines += [provenance]
for name, value in values.items():
    if name not in ('WIDTH','HEIGHT'): lines.append(f'const CGFloat {objc_names[name]} = {number(value)};')
lines += [f'const NSInteger TMLoaderRepeatMin = {motion["repeatMin"]}, TMLoaderRepeatMax = {motion["repeatMax"]};']
for name, path in [('Metal',metal), ('Shaft',shaft), ('Stripe',stripe)]:
    lines += [f'CGPathRef TMLoader{name}Path(void) {{', '    static CGPathRef cached;',
              '    static dispatch_once_t once;', '    dispatch_once(&once, ^{',
              '        CGMutablePathRef path = CGPathCreateMutable();']
    lines += native_path(path, 'objc')
    lines += ['        cached = CGPathCreateCopy(path);', '        CGPathRelease(path);', '    });', '    return cached;', '}']
lines += ['CGColorRef TMLoaderColor(NSString *name) {', '    static NSDictionary<NSString *, id> *colors;',
          '    static dispatch_once_t once;', '    dispatch_once(&once, ^{',
          '        CGColorSpaceRef space = CGColorSpaceCreateWithName(kCGColorSpaceSRGB);',
          '        NSMutableDictionary *values = [NSMutableDictionary dictionary];']
for name, color in loader['colors'].items():
    rgba = [int(color[i:i+2],16)/255 for i in (1,3,5)] + [0 if name == 'highlights' else 1]
    lines += ['        {', f'            CGFloat rgba[] = {{{", ".join(number(v) for v in rgba)}}};',
              '            CGColorRef color = CGColorCreate(space, rgba);',
              f'            values[@"{name}"] = (__bridge id)color;', '            CGColorRelease(color);', '        }']
lines += ['        colors = [values copy];', '        CGColorSpaceRelease(space);', '    });',
          '    return (__bridge CGColorRef)colors[name];', '}', '']
outputs[app / 'tagmaster/TMLogoArtwork.m'] = '\n'.join(lines).encode()

# Launch screens cannot execute app drawing code. Emit a vector-only PDF from
# these same contours. Its 480x800 canvas matches TMLogoBackgroundView's mapping.
scale = min(451 / 299.75076, 774 / 513.52234)
x, y = 241.5 - 299.75076 * scale / 2, 396 - 513.52234 * scale / 2
stream = f'q\n{scale:.9f} 0 0 {-scale:.9f} {x:.9f} {800-y:.9f} cm\n/GS gs\n0.501960784 0.501960784 0.501960784 rg\n'
for contour in contours:
    for command, points in contour:
        stream += (' '.join(map(fmt, points)) + ' ' if points else '') + {'M': 'm', 'C': 'c', 'Z': 'h'}[command] + '\n'
stream += 'f\nQ\n'
objects = [b'<< /Type /Catalog /Pages 2 0 R >>',
           b'<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
           b'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 480 800] /Resources << /ExtGState << /GS 5 0 R >> >> /Contents 4 0 R >>',
           f'<< /Length {len(stream)} >>\nstream\n{stream}endstream'.encode(),
           b'<< /Type /ExtGState /ca 0.298039216 >>']
pdf = b'%PDF-1.4\n'
offsets = [0]
for index, obj in enumerate(objects, 1):
    offsets.append(len(pdf))
    pdf += f'{index} 0 obj\n'.encode() + obj + b'\nendobj\n'
xref = len(pdf)
pdf += f'xref\n0 {len(offsets)}\n0000000000 65535 f \n'.encode()
pdf += b''.join(f'{o:010d} 00000 n \n'.encode() for o in offsets[1:])
pdf += f'trailer\n<< /Size {len(offsets)} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF\n'.encode()
asset = app / 'tagmaster/Images.xcassets/LaunchWatermark.imageset'
outputs[asset / 'LaunchWatermark.pdf'] = pdf
outputs[asset / 'Contents.json'] = b'{\n  "images": [{"filename": "LaunchWatermark.pdf", "idiom": "universal"}],\n  "info": {"author": "xcode", "version": 1},\n  "properties": {"preserves-vector-representation": true}\n}\n'
# --check also guards renderer consumption: matching generated files are not enough
# if a platform quietly reinstates its own period, palette, or hand-drawn cylinder.
if '--check' in sys.argv:
    android = (root / 'Android/TagMaster/src/main/java/depollsoft/tagmaster/BarberPoleLoadingView.kt').read_text()
    ios = (app / 'tagmaster/TMBarberPoleLoadingView.m').read_text()
    for text, required, forbidden in [
        (android, ['BarberPoleLogo.REPEAT_MIN..BarberPoleLogo.REPEAT_MAX', 'phase * BarberPoleLogo.PHASE_MULTIPLIER',
                   'BarberPoleLogo.STRIPE_STEP', 'BarberPoleLogo.AXIS_ANGLE', 'BarberPoleLogo.DURATION_SECONDS',
                   'BarberPoleLogo.RED', 'BarberPoleLogo.BLUE', 'BarberPoleLogo.WHITE',
                   'BarberPoleLogo.METAL_LIGHT', 'BarberPoleLogo.METAL_DARK', 'canvas.clipPath(logo.shaft)',
                   'BarberPoleLogo.COMPACT_HEIGHT', 'BarberPoleLogo.COMPACT_WIDTH'],
                  [r'Color\.', r'PathParser', r'\b(?:96|108|2000)\b', r'getColor\(']),
        (ios, ['TMLoaderMetalPath()', 'kCAFillRuleEvenOdd', 'TMLoaderShaftPath()', 'TMLoaderStripePath()',
               'TMLoaderRepeatMin', 'TMLoaderRepeatMax', 'index * TMLoaderStripeStep',
               'TMLoaderStripeStep * TMLoaderPhaseMultiplier', 'TMLoaderAxisAngle', 'TMLoaderDurationSeconds',
               'TMLoaderArtworkWidth', 'TMLoaderArtworkHeight', 'TMLoaderCompactWidth', 'TMLoaderCompactHeight',
               '[self.axisLayer addSublayer:self.stripes]',
               'TMLoaderColor(@"white")', 'TMLoaderColor(index % 2 == 0 ? @"red" : @"blue")',
               '@"metalDark" : @"metalLight"'],
              [r'\b(?:96|108|216)\b', r'UIBezierPath', r'CGPath(?:Move|Add)', r'UIColor\.', r'colorWithRed:'])]:
        for token in required: assert token in text, f'Renderer bypasses shared definition: {token}'
        for pattern in forbidden: assert not re.search(pattern, text), f'Independent renderer definition: {pattern}'
    query = (app / 'tagmaster/DPTagQueryViewController.m').read_text()
    assert '#import "TMBarberPoleLoadingView.h"' in query, 'Renderer bypasses extracted consumer'
    assert '@implementation TMBarberPoleLoadingView' not in query, 'Independent renderer in query controller'
    compact_style = (root / 'Android/TagMaster/src/main/res/values/barberpole_loader.xml').read_text()
    for dimension in ('width', 'height'):
        assert f'@dimen/barberpole_compact_{dimension}' in compact_style, 'Renderer bypasses shared compact size'
    layout = ET.parse(root / 'Android/TagMaster/src/main/res/layout/tagqueryview.xml')
    view = next(v for v in layout.iter() if v.tag.endswith('BarberPoleLoadingView'))
    assert view.attrib[ns + 'layout_width'] == f'{loader["artworkSize"][0]}dp'
    assert view.attrib[ns + 'layout_height'] == f'{loader["artworkSize"][1]}dp'

for path, data in outputs.items():
    if '--check' in sys.argv:
        assert path.read_bytes() == data, f'Stale generated artwork: {path}'
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
print(f'Canonical match: {len(contours)} contours, {sum(len(c)-2 for c in contours)} cubics; native source and launch PDF verified')
