#!/usr/bin/env python3
"""Offline conversion only. Run from any directory; --check verifies checked-in outputs.
Supports only the canonical file's M/m, c, z grammar and fails on changes.
No runtime parser, third-party package, or build step. Android input is read-only.
"""
from pathlib import Path
from decimal import Decimal as D
import hashlib
import re
import sys
import xml.etree.ElementTree as ET

app = Path(__file__).resolve().parents[1]
root = app.parents[1]
source = root / 'Android/TagMaster/src/main/res/drawable/ic_barberpole.xml'
xml = source.read_bytes()
node = ET.fromstring(xml)
ns = '{http://schemas.android.com/apk/res/android}'
assert node.attrib[ns + 'viewportWidth'] == '299.75076'
assert node.attrib[ns + 'viewportHeight'] == '513.52234'
assert len(node) == 1
raw = node[0].attrib[ns + 'pathData']
tokens = re.findall(r'[A-Za-z]|[-+]?(?:\d*\.\d+|\d+)', raw)
assert not re.sub(r'[A-Za-z]|[-+]?(?:\d*\.\d+|\d+)|[\s,]', '', raw)
contours = []
x = y = D(0)
start = (x, y)
i = 0
command = None
while i < len(tokens):
    if tokens[i].isalpha():
        command = tokens[i]
        i += 1
    if command in ('M', 'm'):
        a, b = map(D, tokens[i:i+2]); i += 2
        x, y = (a, b) if command == 'M' else (x+a, y+b)
        start = (x, y)
        contours.append([('M', (x, y))])
        command = None
    elif command == 'c':
        values = list(map(D, tokens[i:i+6])); i += 6
        points = tuple(v + (x if j % 2 == 0 else y) for j, v in enumerate(values))
        contours[-1].append(('C', points))
        x, y = points[-2:]
    elif command == 'z':
        contours[-1].append(('Z', ()))
        x, y = start
        command = None
    else:
        raise ValueError(f'Unsupported canonical command {command!r}')
assert len(contours) == 9
assert [len(c)-2 for c in contours] == [48, 8, 7, 5, 10, 13, 12, 7, 12]
fmt = lambda v: f'{v:.2f}'
lines = [f'// Generated by tools/generate_logo_artwork.py; do not hand-edit.',
         f'// Canonical ic_barberpole.xml SHA-256: {hashlib.sha256(xml).hexdigest()}',
         '// All nine contours retain their original order and nonzero winding.',
         '#import "TMLogoArtwork.h"', '',
         'const CGFloat TMLogoWidth = 299.75076, TMLogoHeight = 513.52234;', '',
         'static void TMAppendContour(CGMutablePathRef path, NSUInteger contour) {',
         '    switch (contour) {']
for index, contour in enumerate(contours):
    lines.append(f'        case {index}:')
    for command, points in contour:
        if command == 'Z':
            lines.append('            CGPathCloseSubpath(path);')
        else:
            function = 'CGPathMoveToPoint' if command == 'M' else 'CGPathAddCurveToPoint'
            lines.append(f'            {function}(path, NULL, {", ".join(map(fmt, points))});')
    lines.append('            break;')
lines += ['    }', '}', '', 'static CGPathRef full, silhouette, highlights;',
          'static void TMPrepareLogoPaths(void) {', '    static dispatch_once_t once;',
          '    dispatch_once(&once, ^{',
          '        CGMutablePathRef all = CGPathCreateMutable();',
          '        CGMutablePathRef shine = CGPathCreateMutable();',
          '        for (NSUInteger i = 0; i < 9; i++) {',
          '            CGMutablePathRef contour = CGPathCreateMutable();',
          '            TMAppendContour(contour, i);',
          '            CGPathAddPath(all, NULL, contour);',
          '            if (i == 0) silhouette = CGPathCreateCopy(contour);',
          '            if (i == 1 || i == 2 || i == 7 || i == 8) CGPathAddPath(shine, NULL, contour);',
          '            CGPathRelease(contour);', '        }',
          '        full = CGPathCreateCopy(all);', '        highlights = CGPathCreateCopy(shine);',
          '        CGPathRelease(all);', '        CGPathRelease(shine);', '    });', '}', '',
          'CGPathRef TMLogoFullPath(void) { TMPrepareLogoPaths(); return full; }',
          'CGPathRef TMLogoSilhouettePath(void) { TMPrepareLogoPaths(); return silhouette; }',
          'CGPathRef TMLogoHighlightsPath(void) { TMPrepareLogoPaths(); return highlights; }', '']
outputs = {app / 'tagmaster/TMLogoArtwork.m': '\n'.join(lines).encode()}

# Launch screens cannot execute app drawing code. Emit a vector-only PDF from
# these same contours. Its 480x800 canvas matches TMLogoBackgroundView's mapping.
scale = min(451 / 299.75076, 774 / 513.52234)
x, y = 241.5 - 299.75076 * scale / 2, 396 - 513.52234 * scale / 2
stream = f'q\n{scale:.9f} 0 0 {-scale:.9f} {x:.9f} {800-y:.9f} cm\n/GS gs\n0.501960784 0.501960784 0.501960784 rg\n'
for contour in contours:
    for command, points in contour:
        stream += (' '.join(map(fmt, points)) + ' ' if points else '') + {'M': 'm', 'C': 'c', 'Z': 'h'}[command] + '\n'
stream += 'f\nQ\n'
objects = [b'<< /Type /Catalog /Pages 2 0 R >>',
           b'<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
           b'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 480 800] /Resources << /ExtGState << /GS 5 0 R >> >> /Contents 4 0 R >>',
           f'<< /Length {len(stream)} >>\nstream\n{stream}endstream'.encode(),
           b'<< /Type /ExtGState /ca 0.298039216 >>']
pdf = b'%PDF-1.4\n'
offsets = [0]
for index, obj in enumerate(objects, 1):
    offsets.append(len(pdf))
    pdf += f'{index} 0 obj\n'.encode() + obj + b'\nendobj\n'
xref = len(pdf)
pdf += f'xref\n0 {len(offsets)}\n0000000000 65535 f \n'.encode()
pdf += b''.join(f'{o:010d} 00000 n \n'.encode() for o in offsets[1:])
pdf += f'trailer\n<< /Size {len(offsets)} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF\n'.encode()
asset = app / 'tagmaster/Images.xcassets/LaunchWatermark.imageset'
outputs[asset / 'LaunchWatermark.pdf'] = pdf
outputs[asset / 'Contents.json'] = b'{\n  "images": [{"filename": "LaunchWatermark.pdf", "idiom": "universal"}],\n  "info": {"author": "xcode", "version": 1},\n  "properties": {"preserves-vector-representation": true}\n}\n'
for path, data in outputs.items():
    if '--check' in sys.argv:
        assert path.read_bytes() == data, f'Stale generated artwork: {path}'
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
print(f'Canonical match: {len(contours)} contours, {sum(len(c)-2 for c in contours)} cubics; native source and launch PDF verified')
