apply plugin: 'com.android.library'

dependencies {
    api fileTree(include: '*.jar', dir: 'libs')
    api project(':DepollSoftCommon')
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.robolectric:robolectric:4.16.1'
}

android {
    namespace = 'depollsoft.pitchperfect.lib'
    compileSdk 37

    defaultConfig {
        minSdk 23
    }
}
