//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.People
{

    // To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class People { }
#else

	public class People : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public People()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/ScratchPrintingProject;component/SampleData/People/People.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private Person _Person = new Person();

		public Person Person
		{
			get
			{
				return this._Person;
			}
		}
	}

	public class PersonItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Name = string.Empty;

		public string Name
		{
			get
			{
				return this._Name;
			}

			set
			{
				if (this._Name != value)
				{
					this._Name = value;
					this.OnPropertyChanged("Name");
				}
			}
		}

		private string _Address = string.Empty;

		public string Address
		{
			get
			{
				return this._Address;
			}

			set
			{
				if (this._Address != value)
				{
					this._Address = value;
					this.OnPropertyChanged("Address");
				}
			}
		}

		private System.Windows.Media.ImageSource _Photo = null;

		public System.Windows.Media.ImageSource Photo
		{
			get
			{
				return this._Photo;
			}

			set
			{
				if (this._Photo != value)
				{
					this._Photo = value;
					this.OnPropertyChanged("Photo");
				}
			}
		}

		private double _Age = 0;

		public double Age
		{
			get
			{
				return this._Age;
			}

			set
			{
				if (this._Age != value)
				{
					this._Age = value;
					this.OnPropertyChanged("Age");
				}
			}
		}

		private string _Website = string.Empty;

		public string Website
		{
			get
			{
				return this._Website;
			}

			set
			{
				if (this._Website != value)
				{
					this._Website = value;
					this.OnPropertyChanged("Website");
				}
			}
		}

		private Values _Values = new Values();

		public Values Values
		{
			get
			{
				return this._Values;
			}
		}
	}

	public class Person : System.Collections.ObjectModel.ObservableCollection<PersonItem>
	{ 
	}

	public class ValuesItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private double _X = 0;

		public double X
		{
			get
			{
				return this._X;
			}

			set
			{
				if (this._X != value)
				{
					this._X = value;
					this.OnPropertyChanged("X");
				}
			}
		}

		private double _Y = 0;

		public double Y
		{
			get
			{
				return this._Y;
			}

			set
			{
				if (this._Y != value)
				{
					this._Y = value;
					this.OnPropertyChanged("Y");
				}
			}
		}
	}

	public class Values : System.Collections.ObjectModel.ObservableCollection<ValuesItem>
	{ 
	}
#endif
}
