import java.time.Instant
import java.time.LocalDateTime
import java.time.LocalTime
import java.time.format.DateTimeFormatter

// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext.kotlin_version = '1.9.25'
    repositories {
        mavenCentral()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.11.0'

        classpath 'com.google.gms:google-services:4.4.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.25"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

ext {
}

allprojects {
    repositories {
        mavenCentral()
        google()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        maven { url "https://jitpack.io" }
    }
}

subprojects {
    pluginManager.withPlugin("com.android.application") {
        android {
            compileOptions {
                sourceCompatibility = JavaVersion.VERSION_17
                targetCompatibility = JavaVersion.VERSION_17
            }
        }
    }
    pluginManager.withPlugin("com.android.library") {
        android {
            compileOptions {
                sourceCompatibility = JavaVersion.VERSION_17
                targetCompatibility = JavaVersion.VERSION_17
            }
        }
    }
    pluginManager.withPlugin("org.jetbrains.kotlin.android") {
        kotlin {
            jvmToolchain(17)
        }
    }
}

static def getVersionCode(Map args) {
    return getDate() * 1000 + args.build * 10 + args.suffix
}

static def getDate() {
    return Integer.parseInt(DateTimeFormatter.ofPattern("YYMMdd").format(LocalDateTime.now()))
}

configurations {
    all {
        resolutionStrategy {
            dependencySubstitution {
                substitute project(':bindroid') with project(':bindroid:bindroid')
            }
        }
    }
}
