rootProject.name = "depollsoft"

includeBuild 'bindroid'
include ':PitchPerfect', ':depollsoft.lib.kotlin'
//include ':PitchPerfectWear'
include ':PitchPerfectLicense'
include ':TagMaster'
//include ':bindroid:bindroid', ':bindroid:bindroid-kotlin'
include ':DepollSoftCommon.Compat'
include ':PitchPerfectLib'
include ':DepollSoftCommon'
