include ':PitchPerfect', ':PitchPerfectWear'
include ':PitchPerfectLicense'
include ':TagMaster'
include ':Bindroid:BindroidTest'
include ':DepollSoftCommon.Compat'
include ':Bindroid:BindroidSample'
include ':PitchPerfectLib'
include ':facebook'
include ':DepollSoftCommon'
include ':Bindroid:Bindroid'
