apply plugin: 'com.android.application'

dependencies {
    implementation fileTree(include: '*.jar', dir: 'libs')
    implementation 'com.android.support:appcompat-v7'
}

android {
    namespace = 'depollsoft.pitchperfect.license'
    compileSdkVersion 30

    defaultConfig {
        minSdkVersion 16
    }
}
