// Generated by iOS/tagmaster/tools/generate_logo_artwork.py; do not hand-edit.
// Canonical ic_barberpole.xml SHA-256: 94945f08f42627974860086ea78f27f5cd00d0b56e47590bd75191b7891b0c54
// Shared loader SHA-256: 793913bade417a7cf42997f22b98768d292b8aa7e7192bca1abba5a4bbbe76a5
package depollsoft.tagmaster

import android.content.res.Resources
import android.graphics.Path

/** Paths derived from ic_barberpole.xml. Cached once, never mutated by renderers. */
internal class BarberPoleLogo(
    @Suppress("UNUSED_PARAMETER") resources: Resources,
) {
    val metal: Path get() = metalPath
    val shaft: Path get() = shaftPath
    val stripe: Path get() = stripePath

    companion object {
        const val WIDTH = 299.75076f
        const val HEIGHT = 513.52234f
        const val ARTWORK_WIDTH = 34f
        const val ARTWORK_HEIGHT = 58f
        const val COMPACT_HEIGHT = 32f
        const val COMPACT_WIDTH = 18.75862069f
        const val AXIS_ANGLE = 26f
        const val STRIPE_STEP = 108f
        const val PHASE_MULTIPLIER = 2f
        const val DURATION_SECONDS = 2f
        const val REPEAT_MIN = -6
        const val REPEAT_MAX = 6
        val RED: Int = 0xFFBE2A35.toInt()
        val BLUE: Int = 0xFF0063A5.toInt()
        val WHITE: Int = 0xFFFFFFFF.toInt()
        val METAL_LIGHT: Int = 0xFF474747.toInt()
        val METAL_DARK: Int = 0xFFCACACA.toInt()
        private val metalPath =
            Path().apply {
                fillType = Path.FillType.EVEN_ODD
                moveTo(257.1f, 0.46f)
                cubicTo(264.75f, 1.08f, 270.71f, 5f, 277.38f, 8.43f)
                cubicTo(287.57f, 15.03f, 294.38f, 25.3f, 297.82f, 36.84f)
                cubicTo(300.51f, 45.51f, 300.18f, 55.25f, 298.11f, 64.02f)
                cubicTo(295.51f, 69.23f, 294.3f, 74.72f, 290.63f, 79.41f)
                cubicTo(286.57f, 84.8f, 281.86f, 90.49f, 275.81f, 93.7f)
                cubicTo(270.38f, 97.12f, 264.57f, 97.98f, 258.78f, 100.49f)
                cubicTo(263.18f, 103.08f, 267.78f, 104.88f, 271.16f, 108.55f)
                cubicTo(275.93f, 113.53f, 277.83f, 120.23f, 279.04f, 126.84f)
                cubicTo(279.65f, 131.76f, 277.66f, 137.2f, 275.42f, 141.51f)
                cubicTo(273.9f, 143.48f, 269.98f, 143.93f, 268.89f, 146.33f)
                cubicTo(263.44f, 156.8f, 137.71f, 419.6f, 135.26f, 423.6f)
                cubicTo(135.23f, 425.78f, 135.2f, 427.96f, 135.18f, 430.13f)
                cubicTo(132.99f, 433.37f, 131.4f, 436.83f, 128.58f, 439.45f)
                cubicTo(126.56f, 441.22f, 124.05f, 442.49f, 121.82f, 444.01f)
                cubicTo(117.55f, 445.79f, 113.4f, 447.33f, 108.78f, 447.9f)
                cubicTo(105.32f, 447.87f, 101.71f, 446.66f, 98.53f, 445.36f)
                cubicTo(100.26f, 451.6f, 101.61f, 458.27f, 101.48f, 464.76f)
                cubicTo(99.89f, 472.72f, 99.63f, 479.96f, 95.18f, 487.04f)
                cubicTo(91.09f, 494.93f, 84.75f, 501.25f, 77.35f, 506.08f)
                cubicTo(74.25f, 507.57f, 71.26f, 509.03f, 68.01f, 510.48f)
                cubicTo(67.18f, 510.66f, 60.35f, 512.91f, 57.67f, 513.29f)
                cubicTo(50.27f, 513.82f, 43.45f, 513.55f, 36.26f, 511.18f)
                cubicTo(30.46f, 509.27f, 24.76f, 507.03f, 19.89f, 502.76f)
                cubicTo(10.82f, 496.35f, 4.37f, 486.16f, 1.9f, 475.38f)
                cubicTo(-0.09f, 469.24f, -0.44f, 462.69f, 0.49f, 456.32f)
                cubicTo(1.88f, 450.5f, 3.07f, 444.07f, 5.98f, 438.86f)
                cubicTo(9.1f, 433.04f, 12.98f, 428.28f, 17.72f, 423.73f)
                cubicTo(21.53f, 421.11f, 25.42f, 418.61f, 29.48f, 416.39f)
                cubicTo(31.07f, 416.23f, 32.65f, 416.07f, 34.23f, 415.9f)
                cubicTo(32.68f, 414.54f, 29.86f, 412.14f, 28.32f, 410.88f)
                cubicTo(22.61f, 406.25f, 20.97f, 401f, 17.91f, 394.83f)
                cubicTo(17.09f, 391.46f, 16.54f, 387.62f, 17.59f, 384.41f)
                cubicTo(18.3f, 381.54f, 19.21f, 378.74f, 20.16f, 375.94f)
                cubicTo(20.8f, 375.57f, 22.54f, 373.49f, 22.76f, 372.82f)
                cubicTo(24.85f, 371.6f, 26.94f, 370.38f, 29.04f, 369.18f)
                cubicTo(30.68f, 364.89f, 156.02f, 105.93f, 161.11f, 93.93f)
                cubicTo(162.14f, 91.66f, 161.09f, 88.61f, 161.29f, 86.16f)
                cubicTo(162.62f, 83.69f, 164.32f, 81.38f, 165.91f, 79.06f)
                cubicTo(168f, 76.16f, 170.8f, 74.49f, 173.77f, 72.65f)
                cubicTo(177.7f, 71.95f, 181.25f, 70.05f, 185.15f, 69.36f)
                cubicTo(191.24f, 68.46f, 197.81f, 72.31f, 203.84f, 73.63f)
                cubicTo(201.14f, 67.55f, 198.93f, 61.46f, 198.01f, 54.83f)
                cubicTo(197.48f, 50.64f, 198.15f, 46.81f, 198.63f, 42.67f)
                cubicTo(199.2f, 37.7f, 201.93f, 32.76f, 203.62f, 28.02f)
                cubicTo(204.41f, 26.55f, 205.18f, 25.07f, 205.95f, 23.59f)
                cubicTo(208.85f, 19.54f, 211.54f, 15.51f, 215.42f, 12.3f)
                cubicTo(220.01f, 7.76f, 225.43f, 5.77f, 231.1f, 2.92f)
                cubicTo(238.91f, -0.53f, 248.74f, -0.29f, 257.1f, 0.46f)
                close()
                moveTo(29.63f, 431.72f)
                cubicTo(27.59f, 434.12f, 25.1f, 436.15f, 23.21f, 438.65f)
                cubicTo(21.02f, 442.01f, 19.09f, 445.77f, 17.69f, 449.53f)
                cubicTo(15.96f, 454.67f, 16.25f, 459.5f, 16.15f, 464.81f)
                cubicTo(19.1f, 459.94f, 21.94f, 454.72f, 25.72f, 450.44f)
                cubicTo(28.32f, 447.81f, 31.33f, 445.28f, 34.46f, 443.3f)
                cubicTo(40.53f, 439.92f, 46.87f, 438.2f, 53.48f, 436.31f)
                cubicTo(50.58f, 432.27f, 47.22f, 428.75f, 41.96f, 428.37f)
                cubicTo(36.56f, 427.62f, 33.79f, 428.43f, 29.63f, 431.72f)
                close()
                moveTo(62.21f, 415.75f)
                cubicTo(66.46f, 417.66f, 70.05f, 419.42f, 73.84f, 421.74f)
                cubicTo(79.36f, 424.31f, 84.79f, 427.07f, 90.38f, 429.5f)
                cubicTo(95.53f, 431.97f, 100.64f, 435.21f, 106.01f, 437.27f)
                cubicTo(111.14f, 438.53f, 114.9f, 436.39f, 119.3f, 434.2f)
                cubicTo(120.5f, 431.27f, 120f, 431.61f, 119.6f, 429.04f)
                cubicTo(114.37f, 426.79f, 53.24f, 402.78f, 47.5f, 402.32f)
                cubicTo(51.18f, 408.29f, 56.87f, 410.68f, 62.21f, 415.75f)
                close()
                moveTo(179.42f, 80.28f)
                cubicTo(176.95f, 81.88f, 176.23f, 85.47f, 177.93f, 87.86f)
                cubicTo(180.02f, 89.42f, 234.81f, 109.24f, 249.07f, 114.49f)
                cubicTo(248.7f, 113.58f, 248.32f, 112.68f, 247.95f, 111.77f)
                cubicTo(244.57f, 108.93f, 241.53f, 105.82f, 237.69f, 103.56f)
                cubicTo(235.25f, 101.44f, 232.82f, 99.46f, 229.73f, 98.36f)
                cubicTo(225.56f, 96.95f, 200.7f, 83.99f, 192.08f, 79.53f)
                cubicTo(188.48f, 77.26f, 182.77f, 77.8f, 179.42f, 80.28f)
                close()
                moveTo(244.9f, 11.67f)
                cubicTo(239.05f, 12.41f, 232.13f, 13.48f, 227.37f, 17.17f)
                cubicTo(224.25f, 19.36f, 221.4f, 21.86f, 218.81f, 24.65f)
                cubicTo(216.49f, 27.12f, 215.23f, 30.51f, 213.61f, 33.52f)
                cubicTo(211.57f, 39.3f, 210.87f, 44.03f, 211.2f, 50.22f)
                cubicTo(213.49f, 47.03f, 215.93f, 44.24f, 217.66f, 40.69f)
                cubicTo(220.36f, 38.11f, 222.87f, 34.9f, 226.01f, 32.9f)
                cubicTo(229.94f, 30.33f, 234.25f, 27.5f, 238.93f, 26.61f)
                cubicTo(248.48f, 24.54f, 259.32f, 24.09f, 268.64f, 27.41f)
                cubicTo(272.92f, 28.97f, 282.97f, 35.25f, 284f, 36.04f)
                cubicTo(282.16f, 31.88f, 280.36f, 27.88f, 277.03f, 24.66f)
                cubicTo(273.66f, 20.71f, 269.44f, 18.14f, 265.35f, 15.05f)
                cubicTo(258.81f, 12.81f, 251.89f, 10.67f, 244.9f, 11.67f)
                close()
            }
        private val shaftPath =
            Path().apply {
                moveTo(159.01f, 138.81f)
                cubicTo(190f, 131f, 228f, 127f, 253.47f, 140.72f)
                lineTo(122.06f, 413.54f)
                cubicTo(105f, 404f, 65f, 387f, 43f, 379f)
                lineTo(159.01f, 138.81f)
                close()
            }
        private val stripePath =
            Path().apply {
                moveTo(230.13745729f, 131.08178698f)
                cubicTo(224.66252935f, 133.53431962f, 219.74708702f, 135.8253165f, 213.94438061f, 138.43654483f)
                cubicTo(205.70329079f, 142.15315664f, 197.54287339f, 146.37571269f, 189.49296283f, 150.30387188f)
                cubicTo(188.32701783f, 150.85470254f, 187.64073759f, 151.58333399f, 187.4463965f, 152.50774211f)
                cubicTo(186.63656842f, 155.38223288f, 187.58786289f, 193.95851037f, 187.74651418f, 197.88635432f)
                cubicTo(193.13428647f, 195.39742887f, 199.05016635f, 193.65910672f, 204.22803907f, 190.95402967f)
                cubicTo(208.95014108f, 188.60800256f, 213.20180277f, 185.86956668f, 217.91008676f, 183.61736166f)
                cubicTo(225.91456716f, 179.80516363f, 236.43636293f, 174.15914454f, 241.1851375f, 172.14873184f)
                cubicTo(246.87212607f, 169.75583365f, 252.37252896f, 167.27217399f, 258.32341697f, 165.26575724f)
                cubicTo(264.23041842f, 163.26350369f, 270.0214306f, 161.04576008f, 276.05117598f, 159.22326534f)
                cubicTo(286.006199f, 156.53395159f, 296.32266185f, 154.8758253f, 306.8570511f, 152.85250122f)
                cubicTo(308.11129132f, 145.90682713f, 307.0194526f, 118.41652376f, 306.85091176f, 111.57710805f)
                cubicTo(290.12229737f, 111.46373541f, 275.20404393f, 115.37034456f, 259.85487728f, 119.64959583f)
                cubicTo(248.32298855f, 122.72136842f, 236.28635378f, 128.33882679f, 230.13745729f, 131.08178698f)
                close()
            }
    }
}
