#!/bin/sh
# Regenerates the Kotlin TinySoundFont port's golden clips from the C original.
# Writes clips.txt (the event script both sides replay) and golden.raw (16-bit
# mono 44.1 kHz, the clips back to back) into the PitchPerfectLib test resources.
set -eu
HERE=$(cd "$(dirname "$0")" && pwd)
REPO=$(cd "$HERE/../../.." && pwd)
OUT="$REPO/Android/PitchPerfectLib/src/test/resources/soundfont"
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

"$HERE/fetch_tsf.sh" "$WORK"
# No FMA contraction: the JVM rounds every multiply and add separately.
cc -O2 -ffp-contract=off -I"$WORK" "$HERE/tsf_golden.c" -o "$WORK/tsf_golden" -lm

mkdir -p "$OUT"
CLIPS="$OUT/clips.txt"
{
  echo "# TinySoundFont golden clips: generated by scripts/pitchperfect/tinysoundfont/make_golden.sh"
  echo "# clip <name> <samples> / at <sample> preset|tuning|on|off <channel> ... / end"
  # Every Pitch Perfect instrument, low and high, released half-way so the release renders too.
  for program in 0 4 6 11 19 20 21 22 24 46 48 52 56 71 73; do
    for key in 48 72; do
      echo "clip p${program}_k${key} 11025"
      echo "at 0 preset 0 $program"
      echo "at 0 on 0 $key 100"
      echo "at 5512 off 0 $key"
      echo "end"
    done
  done
  # A retuned note, as the app plays a correction plus the reference pitch.
  echo "clip retuned_flute 11025"
  echo "at 0 preset 0 73"
  echo "at 0 tuning 0 -0.4"
  echo "at 0 on 0 69 100"
  echo "at 7000 off 0 69"
  echo "end"
  # A chord on three channels, each with its own preset and tuning, one released early.
  echo "clip chord 11025"
  echo "at 0 preset 0 52"
  echo "at 0 preset 1 0"
  echo "at 0 preset 2 22"
  echo "at 0 tuning 1 0.1"
  echo "at 0 on 0 60 100"
  echo "at 100 on 1 64 100"
  echo "at 300 on 2 67 100"
  echo "at 4000 off 0 60"
  echo "at 8000 off 1 64"
  echo "end"
} > "$CLIPS"

"$WORK/tsf_golden" "$REPO/shared/pitchperfect/PitchPerfectInstruments.sf2" "$CLIPS" "$OUT/golden.raw"
echo "wrote $CLIPS and $OUT/golden.raw ($(wc -c < "$OUT/golden.raw") bytes)"
