workspace 'iOS'

platform :ios, '13.0'
use_frameworks!

project 'depolllib/depolllib.xcodeproj'
project 'pitchperfect/pitchperfectlib/pitchperfectlib.xcodeproj'

inhibit_all_warnings!

def google_utilites
    pod 'GoogleUtilities/AppDelegateSwizzler'
    pod 'GoogleUtilities/Environment'
    pod 'GoogleUtilities/ISASwizzler'
    pod 'GoogleUtilities/Logger'
    pod 'GoogleUtilities/MethodSwizzler'
    pod 'GoogleUtilities/NSData+zlib'
    pod 'GoogleUtilities/Network'
    pod 'GoogleUtilities/Reachability'
    pod 'GoogleUtilities/UserDefaults'
  end

def shared_pods
    pod 'Parse'
    pod 'Bolts/Tasks'
    pod 'GoogleUtilities'
    pod 'Firebase/Auth'
    pod 'Firebase/Firestore'
    pod 'FirebaseFirestore'
    pod 'Firebase/Functions'
    pod 'FirebaseUI/Auth'
    pod 'FirebaseUI/OAuth'
    pod 'FirebaseUI/Email'
    pod 'FirebaseUI/Google'
    pod 'FirebaseUI/Facebook'
    pod 'Protobuf'
    pod 'GTMAppAuth'
    pod 'gRPC-Core'
    pod 'gRPC-C++'
    pod 'GTMSessionFetcher'
end

target 'tagmaster' do
    project 'tagmaster/tagmaster.xcodeproj'
    shared_pods
end

target 'pitchperfect' do
    project 'pitchperfect/pitchperfect.xcodeproj'
    shared_pods
    pod 'Google-Mobile-Ads-SDK'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
        end
    end
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if Gem::Version.new('13.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
    installer.pods_project.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
end
