source 'https://github.com/CocoaPods/Specs.git'

workspace 'iOS'

# Avoid duplicate UUIDs in generated Pods project and speed up generation
install! 'cocoapods', :deterministic_uuids => false

platform :ios, '15.0'
use_frameworks!

project 'depolllib/depolllib.xcodeproj'
project 'pitchperfect/pitchperfectlib/pitchperfectlib.xcodeproj'

inhibit_all_warnings!

def google_utilites
    pod 'GoogleUtilities/AppDelegateSwizzler'
    pod 'GoogleUtilities/Environment'
    pod 'GoogleUtilities/ISASwizzler'
    pod 'GoogleUtilities/Logger'
    pod 'GoogleUtilities/MethodSwizzler'
    pod 'GoogleUtilities/NSData+zlib'
    pod 'GoogleUtilities/Network'
    pod 'GoogleUtilities/Reachability'
    pod 'GoogleUtilities/UserDefaults'
  end

def shared_pods
    pod 'Parse'
    pod 'Bolts/Tasks'
    # 'GoogleUtilities' pulled transitively by Firebase/Google pods; avoid pinning conflicting versions
    pod 'Firebase/Auth'
    pod 'Firebase/Firestore'
    pod 'FirebaseFirestore'
    pod 'Firebase/Functions'
    pod 'FirebaseUI/Auth'
    pod 'FirebaseUI/Email'
    pod 'Protobuf'
    pod 'GTMAppAuth'
    pod 'gRPC-Core'
    pod 'gRPC-C++'
    pod 'GTMSessionFetcher'
end

target 'tagmaster' do
    project 'tagmaster/tagmaster.xcodeproj'
    shared_pods
end

target 'pitchperfect' do
    project 'pitchperfect/pitchperfect.xcodeproj'
    shared_pods
    # Ads SDK not needed for unit tests coverage run
    # pod 'Google-Mobile-Ads-SDK'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
        end
    end
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if Gem::Version.new('13.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
    installer.pods_project.build_configurations.each do |config|
        # Build simulator slices on Apple Silicon; exclude x86_64 to avoid toolchain issues
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "x86_64"
    end
end
