package depollsoft.pitchperfect

/** Tags the screen tests and store captures find controls by; exposed as resource ids. */
object TestTags {
    const val PITCH_INSTRUMENT = "pitchInstrument"
    const val TAB_PITCH_PIPE = "pitchpipe_item"
    const val TAB_NOTES = "notes_item"
    const val TAB_KEYS = "keys_item"
    const val TAB_SONGS = "songs_item"
    const val PAGER = "viewPager"
    const val REMOVE_ADS = "removeAds"
    const val AD_CONTAINER = "adContainer"
    const val NOTE_LIST = "noteListView"
    const val MAJOR_KEYS = "majorKeySignatureListView"
    const val MINOR_KEYS = "minorKeySignatureListView"
    const val MAJOR_MINOR_FAB = "majorMinorFab"
    const val SONG_LIST = "songListView"
    const val SONGS_EMPTY = "sorryText"
    const val ADD_SONG_FAB = "addSongButton"
    const val SET_LIST_SELECTOR = "setListSelector"
    const val SET_LIST_ADD_POSITION = "setListSelectorAdd"
    const val EDIT_SONGS = "editSongsMenuItem"
    const val SORT_SONGS = "sortMenuItem"
    const val SETTINGS = "settingsMenuItem"
    const val OVERFLOW = "overflowMenuButton"
    const val ADD_FROM_LIST = "addFromListMenuItem"
    const val MANAGE_LISTS = "manageListsMenuItem"
    const val DRAG_HANDLE = "dragHandle"
    const val EDIT_SONG_BUTTON = "editButton"
    const val NAME_DIALOG_FIELD = "setListNameInput"
    const val NAME_DIALOG_CONFIRM = "setListNameConfirm"
    const val LOGIN_BUTTON = "login_button"
    const val SONG_TITLE = "songTitleEditText"
    const val KEY_MODE = "keyModeGroup"
    const val SAVE_SONG = "saveSongButton"
    const val SONG_KEY_LIST = "songKeyList"
    const val REMOVE_SONG = "removeSongMenuItem"
    const val CANCEL_SONG = "cancelMenuItem"
    const val OK_SONG = "okMenuItem"
    const val CONFIRM_ADD = "confirmAddSongsMenuItem"
    const val SELECT_ALL = "selectAllSongsMenuItem"
    const val NOTHING_TO_ADD = "addableEmptyText"
    const val ADDABLE_LIST = "addableSongList"
    const val CONFIRM_ADD_BUTTON = "addSongsConfirmButton"
    const val MANAGE_LIST = "setListManageList"
    const val NEW_SET_LIST = "newSetListButton"
    const val ROW_OVERFLOW = "setListRowOverflow"
    const val TOGGLE_NOTES = "toggleNoteCheckBox"
    const val WAKE_LOCK = "wakeLockCheckBox"
    const val CLEAR_SONGS = "clearSongListButton"
    const val WATCH_SECTION = "watchSection"
    const val WATCH_STATUS = "watchStatus"
    const val LOG_IN = "loginButton"
    const val LOG_OUT = "logoutButton"
    const val DELETE_ACCOUNT = "deleteAccountButton"
    const val THEME_SYSTEM = "radio_system"
    const val THEME_LIGHT = "radio_light"
    const val THEME_DARK = "radio_dark"
    const val MANAGE_SUBSCRIPTION = "manageSubscriptionButton"
    const val CHANGELOG = "changelogButton"
    const val PRIVACY_CHOICES = "privacyChoicesButton"

    fun setListPosition(listId: String) = "setListPosition:$listId"

    fun songRow(songId: String) = "song:$songId"

    fun noteRow(index: Int) = "note:$index"

    fun keyRow(index: Int) = "key:$index"

    fun addableRow(songId: String) = "addable:$songId"

    fun manageRow(listId: String) = "setList:$listId"
}
