apply plugin: 'com.android.application'


android {
    namespace = 'depollsoft.pitchperfect'
    compileSdk 35

    signingConfigs {
        release {
            keyAlias System.getenv("ANDROID_UPLOAD_KEY_ALIAS") ?: 'depollsoft'
            keyPassword System.getenv("ANDROID_UPLOAD_KEY_PASSWORD") ?: 'depollsoft'
            storeFile file(System.getenv("ANDROID_UPLOAD_KEYSTORE_PATH") ?: '../debug.jks')
            storePassword System.getenv("ANDROID_UPLOAD_KEYSTORE_PASSWORD") ?: 'depollsoft'
        }
    }

    defaultConfig {
        applicationId "depollsoft.pitchperfect"
        minSdk 26
        targetSdk 35
        versionCode((findProperty('DEPOLLSOFT_PRIVATE_BUILD_NUMBER') ?: getVersionCode(build: 0, suffix: 1)) as Integer)
        versionName "3.0.0"
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        create("private") {
            initWith release
            signingConfig signingConfigs.release
            applicationIdSuffix ".private"
            matchingFallbacks = ['release']
        }
    }
    sourceSets {
        test {
            java.srcDirs = ['src/test/java']
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.google.android.support:wearable:2.9.0'
    compileOnly 'com.google.android.wearable:wearable:2.9.0'
    implementation 'com.google.android.gms:play-services-wearable:18.2.0'
    implementation project(':bindroid')
    implementation project(':PitchPerfectLib')
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.robolectric:robolectric:4.14.1'
}
