apply plugin: 'com.android.application'


android {
    compileSdkVersion 24

    defaultConfig {
        applicationId "depollsoft.pitchperfect"
        minSdkVersion 20
        targetSdkVersion 24
        versionCode 43
        versionName "2.4.1"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.google.android.support:wearable:2.8.1'
    implementation 'com.google.android.wearable:wearable:2.8.1'
    implementation 'com.google.android.gms:play-services-wearable:17.1.0'
    implementation project(':Bindroid:Bindroid')
    implementation project(':PitchPerfectLib')
}
