// Generated by tools/generate_logo_artwork.py; do not hand-edit.
#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN
FOUNDATION_EXPORT const CGFloat TMLogoWidth;
FOUNDATION_EXPORT const CGFloat TMLogoHeight;
FOUNDATION_EXPORT const CGFloat TMLoaderArtworkWidth;
FOUNDATION_EXPORT const CGFloat TMLoaderArtworkHeight;
FOUNDATION_EXPORT const CGFloat TMLoaderAxisAngle;
FOUNDATION_EXPORT const CGFloat TMLoaderStripeStep;
FOUNDATION_EXPORT const CGFloat TMLoaderPhaseMultiplier;
FOUNDATION_EXPORT const CGFloat TMLoaderDurationSeconds;
FOUNDATION_EXPORT const CGFloat TMLoaderCompactWidth;
FOUNDATION_EXPORT const CGFloat TMLoaderCompactHeight;
FOUNDATION_EXPORT const NSInteger TMLoaderRepeatMin, TMLoaderRepeatMax;
// Borrowed immutable process-lifetime paths/colors. Never mutate or release.
// Apply drawing transforms to layers or copies, not the shared provider.
FOUNDATION_EXPORT CGPathRef TMLogoFullPath(void) CF_RETURNS_NOT_RETAINED;
FOUNDATION_EXPORT CGPathRef TMLogoSilhouettePath(void) CF_RETURNS_NOT_RETAINED;
FOUNDATION_EXPORT CGPathRef TMLogoHighlightsPath(void) CF_RETURNS_NOT_RETAINED;
FOUNDATION_EXPORT CGPathRef TMLoaderMetalPath(void) CF_RETURNS_NOT_RETAINED;
FOUNDATION_EXPORT CGPathRef TMLoaderShaftPath(void) CF_RETURNS_NOT_RETAINED;
FOUNDATION_EXPORT CGPathRef TMLoaderStripePath(void) CF_RETURNS_NOT_RETAINED;
FOUNDATION_EXPORT CGColorRef TMLoaderColor(NSString *name) CF_RETURNS_NOT_RETAINED;
NS_ASSUME_NONNULL_END
