// Generated by tools/generate_quartet_artwork.py from shared/tagmaster/quartet-loader.json. Do not edit.
#import "TMQuartetArtwork.h"

const CGFloat TMQuartetWidth = 216.0;
const CGFloat TMQuartetHeight = 96.0;
const CGFloat TMQuartetPeriod = 2.8;
const CGFloat TMQuartetPhaseStart = 0.0;
const CGFloat TMQuartetPhaseEnd = 1.0;
const CGFloat TMQuartetStaffWidth = 1.0;
const CGFloat TMQuartetStaffAlpha = 0.29411765;
const CGFloat TMQuartetX[4] = {108.0, 108.0, 108.0, 108.0};
const CGFloat TMQuartetY[4] = {77.0, 65.0, 53.0, 41.0};
const CGFloat TMQuartetMidi[4] = {60.0, 64.0, 67.0, 70.0};
const CGFloat TMQuartetStill[4] = {1.0, 1.0, 1.0, 1.0};
CGColorRef TMQuartetColor(BOOL dark, BOOL staff) {
    static CGColorRef colors[4]; static dispatch_once_t once;
    dispatch_once(&once, ^{
        CGColorSpaceRef space = CGColorSpaceCreateWithName(kCGColorSpaceSRGB);
        CGFloat c0[] = {0.0, 0.47843137, 0.63921569, 1.0}; colors[0] = CGColorCreate(space, c0);
        CGFloat c1[] = {0.35294118, 0.78431373, 0.98039216, 1.0}; colors[1] = CGColorCreate(space, c1);
        CGFloat c2[] = {0.27843137, 0.27843137, 0.27843137, 0.29411765}; colors[2] = CGColorCreate(space, c2);
        CGFloat c3[] = {0.79215686, 0.79215686, 0.79215686, 0.29411765}; colors[3] = CGColorCreate(space, c3);
        CGColorSpaceRelease(space);
    });
    return colors[(staff ? 2 : 0) + (dark ? 1 : 0)];
}
CGPathRef TMQuartetNotePath(void) {
    static CGPathRef path; static dispatch_once_t once;
    dispatch_once(&once, ^{
        CGMutablePathRef p = CGPathCreateMutable();
        CGPathMoveToPoint(p, NULL, 6.65739561, -2.16311896);
        CGPathAddCurveToPoint(p, NULL, 7.42538979, 0.20052409, 5.06735455, 3.08509671, 1.39057647, 4.27975432);
        CGPathAddCurveToPoint(p, NULL, -2.2862016, 5.47441194, -5.88940143, 4.52676201, -6.65739561, 2.16311896);
        CGPathAddCurveToPoint(p, NULL, -7.42538979, -0.20052409, -5.06735455, -3.08509671, -1.39057647, -4.27975432);
        CGPathAddCurveToPoint(p, NULL, 2.2862016, -5.47441194, 5.88940143, -4.52676201, 6.65739561, -2.16311896);
        CGPathCloseSubpath(p);
        path = CGPathCreateCopy(p); CGPathRelease(p);
    });
    return path;
}
CGPathRef TMQuartetStaffPath(void) {
    static CGPathRef path; static dispatch_once_t once;
    dispatch_once(&once, ^{
        CGMutablePathRef p = CGPathCreateMutable();
        CGPathMoveToPoint(p, NULL, 8.0, 17.0);
        CGPathAddLineToPoint(p, NULL, 208.0, 17.0);
        CGPathMoveToPoint(p, NULL, 8.0, 29.0);
        CGPathAddLineToPoint(p, NULL, 208.0, 29.0);
        CGPathMoveToPoint(p, NULL, 8.0, 41.0);
        CGPathAddLineToPoint(p, NULL, 208.0, 41.0);
        CGPathMoveToPoint(p, NULL, 8.0, 53.0);
        CGPathAddLineToPoint(p, NULL, 208.0, 53.0);
        CGPathMoveToPoint(p, NULL, 8.0, 65.0);
        CGPathAddLineToPoint(p, NULL, 208.0, 65.0);
        path = CGPathCreateCopy(p); CGPathRelease(p);
    });
    return path;
}
CGPathRef TMQuartetStemPath(void) {
    static CGPathRef path; static dispatch_once_t once;
    dispatch_once(&once, ^{
        CGMutablePathRef p = CGPathCreateMutable();
        CGPathMoveToPoint(p, NULL, 113.1, 77.0);
        CGPathAddLineToPoint(p, NULL, 113.1, 16.0);
        CGPathAddLineToPoint(p, NULL, 114.9, 16.0);
        CGPathAddLineToPoint(p, NULL, 114.9, 77.0);
        CGPathCloseSubpath(p);
        path = CGPathCreateCopy(p); CGPathRelease(p);
    });
    return path;
}
CGPathRef TMQuartetLedgerPath(void) {
    static CGPathRef path; static dispatch_once_t once;
    dispatch_once(&once, ^{
        CGMutablePathRef p = CGPathCreateMutable();
        CGPathMoveToPoint(p, NULL, 96.0, 76.5);
        CGPathAddLineToPoint(p, NULL, 120.0, 76.5);
        CGPathAddLineToPoint(p, NULL, 120.0, 77.5);
        CGPathAddLineToPoint(p, NULL, 96.0, 77.5);
        CGPathCloseSubpath(p);
        path = CGPathCreateCopy(p); CGPathRelease(p);
    });
    return path;
}
CGPathRef TMQuartetFlatPath(void) {
    static CGPathRef path; static dispatch_once_t once;
    dispatch_once(&once, ^{
        CGMutablePathRef p = CGPathCreateMutable();
        CGPathMoveToPoint(p, NULL, 89.0, 24.0);
        CGPathAddLineToPoint(p, NULL, 90.8, 24.0);
        CGPathAddLineToPoint(p, NULL, 90.8, 37.5);
        CGPathAddCurveToPoint(p, NULL, 101.0, 30.0, 102.0, 42.0, 89.0, 47.0);
        CGPathCloseSubpath(p);
        CGPathMoveToPoint(p, NULL, 90.8, 40.0);
        CGPathAddLineToPoint(p, NULL, 90.8, 44.0);
        CGPathAddCurveToPoint(p, NULL, 97.0, 40.0, 97.0, 35.0, 90.8, 40.0);
        CGPathCloseSubpath(p);
        path = CGPathCreateCopy(p); CGPathRelease(p);
    });
    return path;
}
CGPathRef TMQuartetLabelPath(void) {
    static CGPathRef path; static dispatch_once_t once;
    dispatch_once(&once, ^{
        CGMutablePathRef p = CGPathCreateMutable();
        CGPathMoveToPoint(p, NULL, 145.0, 26.0);
        CGPathAddCurveToPoint(p, NULL, 132.0, 18.0, 130.0, 42.0, 145.0, 35.0);
        CGPathAddLineToPoint(p, NULL, 145.0, 33.0);
        CGPathAddCurveToPoint(p, NULL, 134.0, 39.0, 135.0, 22.0, 145.0, 28.0);
        CGPathCloseSubpath(p);
        CGPathMoveToPoint(p, NULL, 149.0, 24.0);
        CGPathAddLineToPoint(p, NULL, 159.0, 24.0);
        CGPathAddLineToPoint(p, NULL, 152.0, 37.0);
        CGPathAddLineToPoint(p, NULL, 150.0, 37.0);
        CGPathAddLineToPoint(p, NULL, 156.0, 26.0);
        CGPathAddLineToPoint(p, NULL, 149.0, 26.0);
        CGPathCloseSubpath(p);
        path = CGPathCreateCopy(p); CGPathRelease(p);
    });
    return path;
}
CGPathRef TMQuartetStaffMaskPath(void) {
    static CGPathRef path; static dispatch_once_t once;
    dispatch_once(&once, ^{
        CGMutablePathRef p = CGPathCreateMutable();
        CGPathMoveToPoint(p, NULL, 0.0, 0.0);
        CGPathAddLineToPoint(p, NULL, 216.0, 0.0);
        CGPathAddLineToPoint(p, NULL, 216.0, 96.0);
        CGPathAddLineToPoint(p, NULL, 0.0, 96.0);
        CGPathCloseSubpath(p);
        CGPathMoveToPoint(p, NULL, 114.65739561, 74.83688104);
        CGPathAddCurveToPoint(p, NULL, 115.42538979, 77.20052409, 113.06735455, 80.08509671, 109.39057647, 81.27975432);
        CGPathAddCurveToPoint(p, NULL, 105.7137984, 82.47441194, 102.11059857, 81.52676201, 101.34260439, 79.16311896);
        CGPathAddCurveToPoint(p, NULL, 100.57461021, 76.79947591, 102.93264545, 73.91490329, 106.60942353, 72.72024568);
        CGPathAddCurveToPoint(p, NULL, 110.2862016, 71.52558806, 113.88940143, 72.47323799, 114.65739561, 74.83688104);
        CGPathCloseSubpath(p);
        CGPathMoveToPoint(p, NULL, 114.65739561, 62.83688104);
        CGPathAddCurveToPoint(p, NULL, 115.42538979, 65.20052409, 113.06735455, 68.08509671, 109.39057647, 69.27975432);
        CGPathAddCurveToPoint(p, NULL, 105.7137984, 70.47441194, 102.11059857, 69.52676201, 101.34260439, 67.16311896);
        CGPathAddCurveToPoint(p, NULL, 100.57461021, 64.79947591, 102.93264545, 61.91490329, 106.60942353, 60.72024568);
        CGPathAddCurveToPoint(p, NULL, 110.2862016, 59.52558806, 113.88940143, 60.47323799, 114.65739561, 62.83688104);
        CGPathCloseSubpath(p);
        CGPathMoveToPoint(p, NULL, 114.65739561, 50.83688104);
        CGPathAddCurveToPoint(p, NULL, 115.42538979, 53.20052409, 113.06735455, 56.08509671, 109.39057647, 57.27975432);
        CGPathAddCurveToPoint(p, NULL, 105.7137984, 58.47441194, 102.11059857, 57.52676201, 101.34260439, 55.16311896);
        CGPathAddCurveToPoint(p, NULL, 100.57461021, 52.79947591, 102.93264545, 49.91490329, 106.60942353, 48.72024568);
        CGPathAddCurveToPoint(p, NULL, 110.2862016, 47.52558806, 113.88940143, 48.47323799, 114.65739561, 50.83688104);
        CGPathCloseSubpath(p);
        CGPathMoveToPoint(p, NULL, 114.65739561, 38.83688104);
        CGPathAddCurveToPoint(p, NULL, 115.42538979, 41.20052409, 113.06735455, 44.08509671, 109.39057647, 45.27975432);
        CGPathAddCurveToPoint(p, NULL, 105.7137984, 46.47441194, 102.11059857, 45.52676201, 101.34260439, 43.16311896);
        CGPathAddCurveToPoint(p, NULL, 100.57461021, 40.79947591, 102.93264545, 37.91490329, 106.60942353, 36.72024568);
        CGPathAddCurveToPoint(p, NULL, 110.2862016, 35.52558806, 113.88940143, 36.47323799, 114.65739561, 38.83688104);
        CGPathCloseSubpath(p);
        path = CGPathCreateCopy(p); CGPathRelease(p);
    });
    return path;
}
NSArray<NSNumber *> *TMQuartetSamples(NSUInteger voice) {
    static NSArray *rows; static dispatch_once_t once;
    dispatch_once(&once, ^{ rows = @[
        @[@1.0, @0.97964931, @0.95936748, @0.93922314, @0.91928445, @0.89961887, @0.88029295, @0.86137208, @0.84292029, @0.825, @0.80767186, @0.79099449, @0.77502434, @0.75981543, @0.74541923, @0.73188444, @0.71925688, @0.70757927, @0.69689111, @0.68722858, @0.67862436, @0.67110758, @0.66470367, @0.6594343, @0.65531729, @0.65236657, @0.65059214, @0.65, @0.65059214, @0.65236657, @0.65531729, @0.6594343, @0.66470367, @0.67110758, @0.67862436, @0.68722858, @0.69689111, @0.70757927, @0.71925688, @0.73188444, @0.74541923, @0.75981543, @0.77502434, @0.79099449, @0.80767186, @0.825, @0.84292029, @0.86137208, @0.88029295, @0.89961887, @0.91928445, @0.93922314, @0.95936748, @0.97964931, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0],
        @[@1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @0.98778518, @0.96746755, @0.94726, @0.92723091, @0.90744804, @0.88797834, @0.86888769, @0.85024068, @0.83210041, @0.81452826, @0.79758368, @0.78132402, @0.76580429, @0.751077, @0.73719199, @0.72419624, @0.71213372, @0.70104525, @0.69096834, @0.6819371, @0.67398209, @0.66713022, @0.66140467, @0.65682483, @0.65340618, @0.65116029, @0.65009477, @0.65021321, @0.65151522, @0.6539964, @0.65764834, @0.66245869, @0.66841118, @0.67548565, @0.68365818, @0.69290111, @0.70318317, @0.71446956, @0.72672209, @0.73989931, @0.75395663, @0.76884648, @0.78451848, @0.80091961, @0.81799436, @0.83568495, @0.85393154, @0.87267238, @0.89184405, @0.91138169, @0.93121919, @0.95128941, @0.97152446, @0.99185587, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0],
        @[@1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @0.99592766, @0.97558523, @0.95532542, @0.93521678, @0.91532734, @0.8957244, @0.8764743, @0.85764217, @0.83929174, @0.82148509, @0.80428248, @0.78774212, @0.77191997, @0.75686957, @0.74264185, @0.72928494, @0.71684405, @0.70536127, @0.69487546, @0.68542208, @0.67703314, @0.66973702, @0.66355841, @0.6585182, @0.65463346, @0.65191734, @0.65037901, @0.65002369, @0.65085258, @0.65286288, @0.65604777, @0.6603965, @0.66589433, @0.67252267, @0.68025909, @0.68907741, @0.6989478, @0.70983685, @0.72170772, @0.73452025, @0.74823107, @0.7627938, @0.77815916, @0.79427516, @0.81108727, @0.8285386, @0.8465701, @0.86512076, @0.8841278, @0.90352693, @0.92325248, @0.94323773, @0.96341504, @0.98371614, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0],
        @[@1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @0.98371614, @0.96341504, @0.94323773, @0.92325248, @0.90352693, @0.8841278, @0.86512076, @0.8465701, @0.8285386, @0.81108727, @0.79427516, @0.77815916, @0.7627938, @0.74823107, @0.73452025, @0.72170772, @0.70983685, @0.6989478, @0.68907741, @0.68025909, @0.67252267, @0.66589433, @0.6603965, @0.65604777, @0.65286288, @0.65085258, @0.65002369, @0.65037901, @0.65191734, @0.65463346, @0.6585182, @0.66355841, @0.66973702, @0.67703314, @0.68542208, @0.69487546, @0.70536127, @0.71684405, @0.72928494, @0.74264185, @0.75686957, @0.77191997, @0.78774212, @0.80428248, @0.82148509, @0.83929174, @0.85764217, @0.8764743, @0.8957244, @0.91532734, @0.93521678, @0.95532542, @0.97558523, @0.99592766, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0, @1.0],
    ]; });
    return rows[voice];
}
