#Contains API Secret used to validate your application. Commit to internal source control; avoid making secret public.
#Wed Jul 19 22:21:18 PDT 2017
apiSecret=1996caf35ee55da1e6600835158d88bf39388d5ceb130debffb59c0a08240c13
