workspace '../iOS'

platform :ios, '8.0'

target 'pitchperfect' do
    pod 'Parse'
    pod 'Parse/FacebookUtils'
    pod 'FBSDKCoreKit'
    pod 'Firebase/Analytics'
    pod 'Firebase/AdMob'
    pod 'Fabric'
    pod 'Crashlytics'
end