name: GeoIP update

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 3

jobs:
  update-geoip:
    name: Update geoip data
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: NPM install
        run: npm install geoip-lite
      - name: Download using gsutil
        run: gsutil -m cp -r gs://depollsoft-build-data/node_modules/geoip-lite/data node_modules/geoip-lite/
        continue-on-error: true
      - name: Update
        run: cd node_modules/geoip-lite && npm run-script updatedb license_key=${{ secrets.MAXMIND_LICENSE_KEY }}
      - name: Upload using gsutil
        run: gsutil -m cp -r node_modules/geoip-lite/data gs://depollsoft-build-data/node_modules/geoip-lite/
